# ARG BASE_IMAGE=jupyter/minimal-notebook:python-3.11.5
FROM jupyter/base-notebook:latest

# Set the working directory to /app
USER root

RUN adduser -D myuser
USER myuser

# local contents of the current directory to /app in the container
COPY . /app
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=builder /usr/local/bin/gunicorn /usr/local/bin/gunicorn
COPY --from=builder /app .

RUN pip install --no-cache-dir -r requirements.txt

RUN apk add --no-cache \
    package1 \
    package2 \
    && rm -rf /var/cache/apk/*

# environment variables
ENV FLASK_APP=app.py \
    FLASK_RUN_HOST=0.0.0.0 \
    FLASK_RUN_PORT=5000

# port
EXPOSE 8888

CMD ["jupyter", "notebook", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]

COPY mqtt-server-flow.json

RUN pip cache purge 
